security:
  jwt:
    secret-key: "verysecretkeyomg"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/
    username: isa
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8090

